package com.hide1963.test01.model;

public class Table02 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.table02.id
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.table02.sqlno
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    private Integer sqlno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.table02.bookname
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    private String bookname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.table02.id
     *
     * @return the value of public.table02.id
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.table02.id
     *
     * @param id the value for public.table02.id
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.table02.sqlno
     *
     * @return the value of public.table02.sqlno
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    public Integer getSqlno() {
        return sqlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.table02.sqlno
     *
     * @param sqlno the value for public.table02.sqlno
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    public void setSqlno(Integer sqlno) {
        this.sqlno = sqlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.table02.bookname
     *
     * @return the value of public.table02.bookname
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.table02.bookname
     *
     * @param bookname the value for public.table02.bookname
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }
}