package com.hide1963.test01.model;

public class Table01 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.table01.id
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.table01.authorname
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    private String authorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.table01.category
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.table01.id
     *
     * @return the value of public.table01.id
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.table01.id
     *
     * @param id the value for public.table01.id
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.table01.authorname
     *
     * @return the value of public.table01.authorname
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    public String getAuthorname() {
        return authorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.table01.authorname
     *
     * @param authorname the value for public.table01.authorname
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    public void setAuthorname(String authorname) {
        this.authorname = authorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.table01.category
     *
     * @return the value of public.table01.category
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.table01.category
     *
     * @param category the value for public.table01.category
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    public void setCategory(String category) {
        this.category = category;
    }
}