package com.hide1963.test01.mapper;

import com.hide1963.test01.model.Table02;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface Table02Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.table02
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    int insert(Table02 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.table02
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    List<Table02> selectAll();
}