package com.hide1963.test01.mapper;

import com.hide1963.test01.model.Table01;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface Table01Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.table01
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    int insert(Table01 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.table01
     *
     * @mbg.generated Wed Oct 29 10:59:13 JST 2025
     */
    List<Table01> selectAll();
}